### ISSUE TITLE
Survey API Handling of Section Scores and Responses

### ISSUE THREAD

**Issue by CTAJavier** [hserv/coordinated-entry#29]
We need changes to the Survey API to easily store all survey responses including Section scoring required for VI SPDAT Functionality.

Changes needed discussion here https://docs.google.com/document/d/1HxbgZd5doiKuUQNAG8RqycRhxYVEQIqu70izqcBO-XM/edit?usp=sharing

**Comment by eric-jahn** [comment]
pasting the contents of the doc here, so it's preserved at that point in time: 

Questions and changes
Primary Concern
Posting responses for questions including section scores
There is currently no way to post section scores, 
	VI-SPDAT calculations are not calculated per question but per section, e.g if Question 1 and question 2 are yes then score 1, or if question 3 and 4 are yes score 1 else if question 4 and 5 are yes score 2 points else if question 3 and 5 are yes score 3 points. Not all of our questions will have scores but we need functionality to post scores at either the question or the section level. And the matching/final VI score should be taken by adding the section scores not just the question scores.

Other thoughts
Why are picklist values not referenced in the response ?
What is the point of the pick lists if they actual response does not reference them? Does it really store the actual text submitted?  We do not have a picklist table we are storing our picklist values as an array within our question table. We can work with this but just wondering why you have separate picklist tables instead of handling things with arrays as we do.

**Comment by eric-jahn** [comment]
breaking out the picklist issue as a separate issue #30

**Comment by eric-jahn** [comment]
@CTAJavier: so if we add POST /scores to our API would it resolve this issue (just issue #29, not #30)?  Then you can override the section scores...

**Comment by CTAJavier** [comment]
Yes, that would be fine I guess the important part is going to be that the sections line up so the post would have to include sectionID and section score as well as response ID

**Comment by desaiuditd** [comment]
https://hmislynk.slack.com/archives/home_app_support/p1473193490000129

either we need to add `score` field either in `POST /sections` or `POST /questions`

**Comment by suryayadavalli** [comment]
@desaiuditd : 
in POST /sections  - there is a element called sectionWeight and in POST /questions there is an element questionWeight - which accept the scores for a section and for a question respectively.  Just wondering if these fields would suffice passing on scores .

**Comment by suryayadavalli** [comment]
closing this issue as the APIs currently allow posting scores
