### ISSUE TITLE
Cease Ignoring Invalid Project eligibility conditions and move on with matching process

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#41]

**Comment by eric-jahn** [comment]
@suryayadavalli: Is this issue still open?

**Comment by suryayadavalli** [comment]
@eric-jahn : This is still a open issue for us. We prioritized this however, haven't addressed this yet

**Comment by CTAJavier** [comment]
Hey Surya, what is going on with this?

**Comment by eric-jahn** [comment]
@CTAJavier : We have created a API endpoints for reviewing any occurrences of invalid matches for both projects and individuals, at every step of the match process.  That issue was https://github.com/hserv/coordinated-entry/issues/98 which has a link to the documentation.  So you can see where invalid criteria exist, and fix them when they occur.
