### ISSUE TITLE
[Housing Match API] Missing attributes in GET /matches

### ISSUE THREAD

**Issue by desaiuditd** [hserv/coordinated-entry#77]
https://hmislynk.slack.com/archives/home_app_support/p1477437896000060

Getting wrong response in Matching API service

Request
```
GET /house-matching-api/matches HTTP/1.1
Host: www.hmislynk.com
X-HMIS-TrustedApp-Id: 16631CFE-6909-4AC1-B4EB-57902AC7AF0A
Authorization: HMISUserAuth session_token=77A56458170E4024AC05A213B7527265FB85BC7DA51F414FB7A90B1AE86AD428
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Postman-Token: 1d0457d3-caac-e27a-7812-4e7b5965a3c8
```

Response
```
{
  "links": [
    {
      "rel": "self",
      "href": "https://www.hmislynk.com/house-matching-api/matches"
    }
  ],
  "page": {
    "size": 20
  }
}
```

The `content` is missing as per the documentation.

This is happening when I login from `monterey@hmislynk.com` user.

It works properly when I login from `desaiuditd@gmail.com`.

**Comment by suryayadavalli** [comment]
monterey@hmislynk.com belongs to a different project group M0001. There are clients that belong to project group and surveys , however  there are no scores are associated to these clients for these surveys.

When POST /matches is called , it first gets the eligible clients (clients who are surveyed) and then execute the matching process to assign the housing units to those eligible clients , if the criteria is met.

In this case,  since no clients are surveyed (no scores present for these clients), the matching API doesn't return any results.

**Comment by suryayadavalli** [comment]
![image](https://cloud.githubusercontent.com/assets/10738348/19715513/8d5cb2da-9b0a-11e6-8c46-43a1aa6139b6.png)

**Comment by desaiuditd** [comment]
Okay. That makes sense. but can you at least send empty array for `content` ? Because, not having `content` field at all will break our code at HOME end.

@suryayadavalli

**Comment by suryayadavalli** [comment]
Resolved. Deployed in production. Please check and let us know if you see any further issues. Thanks !
